ALTER TABLE "StorageLocation" ADD COLUMN "isDefault" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Order" ADD COLUMN "locationId" TEXT REFERENCES "StorageLocation"("id") ON DELETE SET NULL ON UPDATE CASCADE;
